name: Load testing workflow
on: [push, workflow_dispatch]

jobs:
  test:
    name: Run load test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 local test
        uses: k6io/action@v0.1
        with:
          filename: test.js
          flags: --out influxdb=http://4b2c-2405-201-d001-402d-d0c6-3439-9dfe-e695.ngrok.io